# network architecture
# encoder related
elayers: 4
eunits: 2048
# decoder related
dlayers: 1
dunits: 1024
# attention related
adim: 256
aheads: 4
# transformer related
transformer-input-layer: conv2d
model-module: "espnet.nets.pytorch_backend.e2e_asr_dynamicformer:E2E"

# hybrid CTC/attention
mtlalpha: 0.3

# label smoothing
lsm-weight: 0.1

# minibatch related
batch-size: 16
maxlen-in: 512  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
sortagrad: 0 
opt: noam
epochs: 300
dropout-rate: 0.1
accum-grad: 2
grad-clip: 5
patience: 0

# transformer specific setting
transformer-lr: 1.0
transformer-warmup-steps: 6000
transformer-attn-dropout-rate: 0.0
transformer-length-normalized-loss: False
transformer-init: pytorch

# conformer specific setting
transformer-encoder-pos-enc-layer-type: rel_pos
transformer-encoder-selfattn-layer-type: rel_selfattn
macaron-style: true
use-cnn-module: true
cnn-module-kernel: 31

# lightweight/dynamic convolution specific setting
# decoder not using
lightconv-encoder-layer-type: dynamicconv
lightconv-wshare: 4
lightconv-dim: 256
lightconv-encoder-kernel-length: "31_25_17_9"